#!/usr/bin/python3

print ("\n\t\t\t***Método de cifrado***")
print ("\n\t\t\t   Respuesta: IBM")

def cifrado():
    lr = []
    clave = clave_bin()
    msn = mensaje_bin()
    K = generacion_subclaves(clave)
    L,R = IP(msn)
    lr.append(L)
    lr.append(R)
    for i in range(0,16):    
        ff = F(lr[i+1][0:],K[i])
        lr.append(xor(lr[i],ff))
    
    final = IP__1(lr[-1]+lr[-2])
    a = "".join(str(i) for i in final)
    cifrado = hex(int(a,2))[2::]
    return cifrado.upper()